name: flexfold
description: FlexScaffold is an animated, responsive and adaptive application scaffold.
version: 0.0.1
homepage: https://github.com/rydmike/flexfold
environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  collection:
  flutter_test:
    sdk: flutter
  test:

flutter:
  uses-material-design: true
