name: flexfold_demo
description: Flexfold responsive scaffold package demo.
publish_to: 'none'
version: 0.90.3
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  # Prebuilt transition animations (by Google, flutter.dev).
  # https://pub.dev/packages/animations
  animations: ^2.0.7

  # Used by Cupertino classes for iOS style icons (by Google, flutter.dev).
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.5

  # Device preview to switch simulated devices at runtime (by Aloïs Deniel)
  # https://pub.dev/packages/device_preview
  device_preview: ^1.1.0

  # Color picker package (by Mike Rydstrom, rydmike.com).
  # https://pub.dev/packages/flex_color_picker
  flex_color_picker: ^2.3.1
  #flex_color_picker:
  #  path: ../../flex_color_picker

  # Color scheme package (by Mike Rydstrom, rydmike.com).
  # https://pub.dev/packages/flex_color_scheme
  flex_color_scheme: ^6.1.1
  # flex_color_scheme:
  #  path: ../../flex_color_scheme

  # Responsive and adaptive scaffold package (by Mike Rydstrom, rydmike.com).
  # https://pub.dev/packages/flex_color_scheme
  flexfold:
    path: ../

  # The Flutter SDK
  flutter:
    sdk: flutter

  # Riverpod, next generation version of Provider (by Remi Rousselet).
  # https://pub.dev/packages/flutter_riverpod:
  flutter_riverpod: ^2.1.1

  # SVG file drawing, used for Undraw Asset Images (by dnfield.dev).
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.1.6

  # Easy-to-use URL-based router for Flutter web, mobile and desktop apps.
  # https://pub.dev/packages/go_router (by Chris Sells)
  go_router: ^5.2.0

  # Google fonts (by Google material.io).
  # https://pub.dev/packages/google_fonts
  google_fonts: ^3.0.1

  # Lightweight fast key-value db in pure Dart (by Simon Leier, hivedb.dev).
  # https://pub.dev/packages/hive
  hive: ^2.2.3

  # Get dominant colors from an image (by Google, flutter.dev).
  # https://pub.dev/packages/palette_generator:
  palette_generator: ^0.3.3+2

  # Commonly used directories on host platform file systems.
  # https://pub.dev/packages/path_provider (by Google, flutter.dev).
  path_provider: ^2.0.11

  # Easy-to-use URL-based router for Flutter web, mobile and desktop apps.
  # https://pub.dev/packages/routemaster (by Tom Gilder)
  # routemaster: ^0.10.0-dev5
  #routemaster:
  #  path: ../../../tomgilder/routemaster

  # Plasma liquid animation from simple_animations 3.x (by felix-blaschke.de).
  # https://pub.dev/packages/sa3_liquid
  sa3_liquid: ^1.0.1

  # Used for launching a WEB URL (by Google flutter.dev).
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.7

dev_dependencies:
  # Tool for making native launcher icons for Android and iOS
  # (by https://github.com/fluttercommunity/community)
  # https://pub.dev/packages/flutter_launcher_icons
  # flutter_launcher_icons: ^0.9.0

  # Flutter testing toolkit SDK
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # all used image assets.
  assets:
    - assets/images/
    - assets/theme_images/
#  fonts:
#    # While Roboto is included in Android Flutter, it is not available on all platforms
#    # to ensure that we get the actual Roboto font on all platforms we include it as an asset.
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
#          weight: 100
#        - asset: assets/fonts/Roboto/Roboto-Light.ttf
#          weight: 300
#        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/Roboto/Roboto-Black.ttf
#          weight: 900
#        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
#          weight: 100
#          style: italic
#        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
#          weight: 300
#          style: italic
#        - asset: assets/fonts/Roboto/Roboto-RegularItalic.ttf
#          weight: 400
#          style: italic
#        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
#          weight: 500
#          style: italic
#        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
#          weight: 700
#          style: italic
#        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
#          weight: 900
#          style: italic
#    - family: Rubik Mono One
#      fonts:
#        - asset: assets/fonts/rubikmono/RubikMonoOne-Regular.ttf
